name: seo_renderer
description: A flutter plugin to render text widgets as html for SEO purpose.
version: 0.0.2
homepage: https://github.com/iamSahdeep/seo_renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
